name 'puppetlabs-drbd'
version '0.1.0'
source 'git://github.com/puppetlabs/puppetlabs-drbd.git'
author 'Puppet Labs'
license 'Apache 2.0'
summary 'DRBD module'
description 'DRBD module'
project_page 'http://github.com/puppetlabs/puppetlabs-drbd'
dependency 'ripienaar/concat', '>= 0.1.0'
